model:
  model_name: transformer
  patch_embed_name: vanilla
  hidden_channels: 768
  mid_dim: 2048
  num_layers: 12
  num_heads: 12
  use_ape: True
train:
  weight_decay: 0.05
  adam_beta1: 0.9
  adam_beta2: 0.95
  clip_grad: 1.0
