model:
  model_name: wmtc
  patch_embed_name: freq
  hidden_channels: 192
  mid_dim: 512
  num_layers: 12
  num_heads: 3
  use_ape: True
  num_res_blocks: 4
  channel_multipliers: [1, 2, 2, 4]
  hidden_channels_wt: 128
train:
  weight_decay: 0.05
  adam_beta1: 0.9
  adam_beta2: 0.95
  clip_grad: 1.0
