model:
  model_name: wmtc
  patch_embed_name: freq
  hidden_channels: 768
  mid_dim: 2048
  num_layers: 12
  num_heads: 12
  use_ape: True
  num_res_blocks: 1
  channel_multipliers: [1, 1, 2, 2]
  hidden_channels_wt: 512
train:
  weight_decay: 0.05
  adam_beta1: 0.9
  adam_beta2: 0.95
  clip_grad: 1.0
